// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyejlAoEYV3vMqKnJX5t8jpc_AZcxm_QI',
    appId: '1:276337970524:web:1384914e9643893b620599',
    messagingSenderId: '276337970524',
    projectId: 'newedtech-aa20a',
    authDomain: 'newedtech-aa20a.firebaseapp.com',
    databaseURL: 'https://newedtech-aa20a-default-rtdb.firebaseio.com',
    storageBucket: 'newedtech-aa20a.firebasestorage.app',
    measurementId: 'G-P2TX64Y48Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfBtwJPwlnC1VqF6zunN9edylQt9SqKFY',
    appId: '1:276337970524:android:5c8d975c2e200e2f620599',
    messagingSenderId: '276337970524',
    projectId: 'newedtech-aa20a',
    databaseURL: 'https://newedtech-aa20a-default-rtdb.firebaseio.com',
    storageBucket: 'newedtech-aa20a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXf-X4Ox0BSV6H4wKuo7uUFecXMwL3CLA',
    appId: '1:276337970524:ios:0cce2231c0a732e9620599',
    messagingSenderId: '276337970524',
    projectId: 'newedtech-aa20a',
    databaseURL: 'https://newedtech-aa20a-default-rtdb.firebaseio.com',
    storageBucket: 'newedtech-aa20a.firebasestorage.app',
    androidClientId: '276337970524-1tq365b6p7p3l47jgqjkuki50lajo4p2.apps.googleusercontent.com',
    iosClientId: '276337970524-4semnfbfu4ptbspvomj3qm0t0n15cqve.apps.googleusercontent.com',
    iosBundleId: 'com.examplan.b',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXf-X4Ox0BSV6H4wKuo7uUFecXMwL3CLA',
    appId: '1:276337970524:ios:3109d10e1d28df94620599',
    messagingSenderId: '276337970524',
    projectId: 'newedtech-aa20a',
    databaseURL: 'https://newedtech-aa20a-default-rtdb.firebaseio.com',
    storageBucket: 'newedtech-aa20a.firebasestorage.app',
    androidClientId: '276337970524-1tq365b6p7p3l47jgqjkuki50lajo4p2.apps.googleusercontent.com',
    iosClientId: '276337970524-66m0fdu4oomk042d30qjhl9pvbg4a989.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineteachingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyejlAoEYV3vMqKnJX5t8jpc_AZcxm_QI',
    appId: '1:276337970524:web:1384914e9643893b620599',
    messagingSenderId: '276337970524',
    projectId: 'newedtech-aa20a',
    authDomain: 'newedtech-aa20a.firebaseapp.com',
    databaseURL: 'https://newedtech-aa20a-default-rtdb.firebaseio.com',
    storageBucket: 'newedtech-aa20a.firebasestorage.app',
    measurementId: 'G-P2TX64Y48Y',
  );

}
